---
- name: Ensure group admin exists
  group:
    name: admin
    state: present
- name: Create user accounts
  user:
    name: "{{ item }}"
    shell: "/bin/bash"
    groups: [admin]
    append: yes
  with_items: "{{ users }}"
- name: Add authorized keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
  with_items: "{{ users }}"
- name: Allow admin users to sudo without a password
  lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    regexp: "^%admin"
    line: "%admin ALL=(ALL) NOPASSWD: ALL"