# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
end

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.hostname="kubemaster"
    master.vm.box="generic/centos7"
    master.vm.network :private_network, ip: "10.50.10.10"
    master.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 2]
    end
    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible_provisioning/playbook.yml"
      ansible.compatibility_mode = "2.0"
      ansible.verbose = true
      ansible.config_file = "../ansible_provisioning/ansible.cfg"
      ansible.inventory_path = "../ansible_provisioning/inventory/hosts"
    end
  end

  N = 3

  (1..N).each do |i|
  node_id = "node#{i}"
  config.vm.define node_id do |node|
    node.vm.hostname = "#{node_id}"
      node.vm.box="generic/centos7"
      node.vm.network :private_network, ip:"10.50.10.1#{i}"
      node.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--cpus", 2]
      end
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible_provisioning/playbook.yml"
        ansible.compatibility_mode = "2.0"
        ansible.verbose = true
        ansible.config_file = "../ansible_provisioning/ansible.cfg"
        ansible.inventory_path = "../ansible_provisioning/inventory/hosts"
      end
    end
  end
end