---

- name: ensure nginx is at the latest version
  yum: 
    name: nginx
    state: latest
  
- name: start nginx
  service:
      name: nginx
      state: started

- name: copy the nginx config file and restart nginx
  template:
    src: loadbalancer.conf.j2
    dest: /etc/nginx/loadbalancer.conf

- name: stat nginx.conf
  stat: 
    path: /etc/nginx/nginx.conf
  register: default_stat

- name: rename the default.conf
  command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.disabled
  when: default_stat.stat.exists

- name: rename the default.conf
  command: mv /etc/nginx/loadbalancer.conf /etc/nginx/nginx.conf

- name: restart nginx
  service:
    name: nginx
    state: restarted
