---
- name: Create the images directory
  file:
    path: /var/lib/rancher/rke2/agent/images
    state: directory

- name: download rke2 images
  get_url: 
    url: "https://github.com/rancher/rke2/releases/download/{{ rke_version | urlencode }}/rke2-images.linux-amd64.tar.gz"
    dest: /var/lib/rancher/rke2/agent/images/rke2-images.linux-amd64.tar.gz

- name: Create an rke2 directory
  file:
    path: /etc/rancher/rke2
    state: directory

- name: Create config file
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml

- name: download the files for systemd
  unarchive: 
    src: "https://github.com/rancher/rke2/releases/download/{{ rke_version | urlencode }}/rke2.linux-amd64.tar.gz"
    dest: /tmp/rke2_files
    remote_src: yes

- name: Copy the rke binary
  copy:
    src: /tmp/rke2_files/bin/rke2
    dest: /usr/local/bin/rke2
    remote_src: yes

- name: Making RKE2 executable
  file:
    dest: /usr/local/bin/rke2
    mode: a+x

- name: Create a temp directory
  file:
    path: /tmp/rke2_files
    state: directory

- name: copy service files under systemd
  copy:
    src: "/tmp/rke2_files/lib/systemd/system/{{ item }}"
    dest: /etc/systemd/system/
    remote_src: yes
  with_items:
    - rke2-server.service
    - rke2-agent.service

- name: remove files from tmp
  file:
    path: /tmp/rke2_files
    state: absent

- name: Enable and start rke2-server.service
  ansible.builtin.systemd:
    name: rke2-server.service
    state: started
    enabled: yes